/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as FirstAidRouteImport } from './routes/first-aid'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ProfessionalRouteImport } from './routes/professional'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as SymptomCheckerRouteImport } from './routes/symptom-checker'
import { Route as ConditionsConditionIdRouteImport } from './routes/conditions.$conditionId'
import { Route as FirstAidIndexRouteImport } from './routes/first-aid.index'
import { Route as FirstAidSlugRouteImport } from './routes/first-aid.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidRoute = FirstAidRouteImport.update({
  id: '/first-aid',
  path: '/first-aid',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessionalRoute = ProfessionalRouteImport.update({
  id: '/professional',
  path: '/professional',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const SymptomCheckerRoute = SymptomCheckerRouteImport.update({
  id: '/symptom-checker',
  path: '/symptom-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsConditionIdRoute = ConditionsConditionIdRouteImport.update({
  id: '/conditions/$conditionId',
  path: '/conditions/$conditionId',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAidIndexRoute = FirstAidIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FirstAidRoute,
} as any)
const FirstAidSlugRoute = FirstAidSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => FirstAidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/first-aid': typeof FirstAidRouteWithChildren
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/professional': typeof ProfessionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
  '/first-aid/$slug': typeof FirstAidSlugRoute
  '/first-aid/': typeof FirstAidIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/professional': typeof ProfessionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
  '/first-aid/$slug': typeof FirstAidSlugRoute
  '/first-aid': typeof FirstAidIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/auth': typeof AuthRoute
  '/emergency': typeof EmergencyRoute
  '/first-aid': typeof FirstAidRouteWithChildren
  '/history': typeof HistoryRoute
  '/library': typeof LibraryRoute
  '/professional': typeof ProfessionalRoute
  '/reset-password': typeof ResetPasswordRoute
  '/results': typeof ResultsRoute
  '/symptom-checker': typeof SymptomCheckerRoute
  '/conditions/$conditionId': typeof ConditionsConditionIdRoute
  '/first-aid/$slug': typeof FirstAidSlugRoute
  '/first-aid/': typeof FirstAidIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/emergency'
    | '/first-aid'
    | '/history'
    | '/library'
    | '/professional'
    | '/reset-password'
    | '/results'
    | '/symptom-checker'
    | '/conditions/$conditionId'
    | '/first-aid/$slug'
    | '/first-aid/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/auth'
    | '/emergency'
    | '/history'
    | '/library'
    | '/professional'
    | '/reset-password'
    | '/results'
    | '/symptom-checker'
    | '/conditions/$conditionId'
    | '/first-aid/$slug'
    | '/first-aid'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/auth'
    | '/emergency'
    | '/first-aid'
    | '/history'
    | '/library'
    | '/professional'
    | '/reset-password'
    | '/results'
    | '/symptom-checker'
    | '/conditions/$conditionId'
    | '/first-aid/$slug'
    | '/first-aid/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  EmergencyRoute: typeof EmergencyRoute
  FirstAidRoute: typeof FirstAidRouteWithChildren
  HistoryRoute: typeof HistoryRoute
  LibraryRoute: typeof LibraryRoute
  ProfessionalRoute: typeof ProfessionalRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ResultsRoute: typeof ResultsRoute
  SymptomCheckerRoute: typeof SymptomCheckerRoute
  ConditionsConditionIdRoute: typeof ConditionsConditionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid': {
      id: '/first-aid'
      path: '/first-aid'
      fullPath: '/first-aid'
      preLoaderRoute: typeof FirstAidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professional': {
      id: '/professional'
      path: '/professional'
      fullPath: '/professional'
      preLoaderRoute: typeof ProfessionalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/symptom-checker': {
      id: '/symptom-checker'
      path: '/symptom-checker'
      fullPath: '/symptom-checker'
      preLoaderRoute: typeof SymptomCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions/$conditionId': {
      id: '/conditions/$conditionId'
      path: '/conditions/$conditionId'
      fullPath: '/conditions/$conditionId'
      preLoaderRoute: typeof ConditionsConditionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-aid/': {
      id: '/first-aid/'
      path: '/'
      fullPath: '/first-aid/'
      preLoaderRoute: typeof FirstAidIndexRouteImport
      parentRoute: typeof FirstAidRoute
    }
    '/first-aid/$slug': {
      id: '/first-aid/$slug'
      path: '/$slug'
      fullPath: '/first-aid/$slug'
      preLoaderRoute: typeof FirstAidSlugRouteImport
      parentRoute: typeof FirstAidRoute
    }
  }
}

interface FirstAidRouteChildren {
  FirstAidSlugRoute: typeof FirstAidSlugRoute
  FirstAidIndexRoute: typeof FirstAidIndexRoute
}

const FirstAidRouteChildren: FirstAidRouteChildren = {
  FirstAidSlugRoute: FirstAidSlugRoute,
  FirstAidIndexRoute: FirstAidIndexRoute,
}

const FirstAidRouteWithChildren = FirstAidRoute._addFileChildren(
  FirstAidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  EmergencyRoute: EmergencyRoute,
  FirstAidRoute: FirstAidRouteWithChildren,
  HistoryRoute: HistoryRoute,
  LibraryRoute: LibraryRoute,
  ProfessionalRoute: ProfessionalRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ResultsRoute: ResultsRoute,
  SymptomCheckerRoute: SymptomCheckerRoute,
  ConditionsConditionIdRoute: ConditionsConditionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
